### ISSUE TITLE
Loading starts firstly if and only if you are scrolling a bit

### ISSUE THREAD

**Issue by OneDivZero** [eisbehr-/jquery.lazy#1]
Well, the subject tells the whole story. I read anywhere on stackoverflow for another plugin a similiar issue. But i forgott to bookmark it. Maybe it's quickly fixed ?!

**Comment by krzyko** [comment]
Good day. I have a site snapshot here: http://www.sii.org.pl/fade.html and the problem persist in latest IE, Chrome and FF. You have to scroll down two or three pages and the refresh the page. It looks like some weird "race condition" because sometimes page loads correctly. Moreover, adding "combined: true" (with eg. 250ms delay) seems to fix the issue (live webpage here: http://www.sii.org.pl).

**Comment by krzyko** [comment]
Good day, problem is probably related to css style: "#feedinfo a.clicky img.lazy {height: auto !important; }" because removing this style makes lazyload work flawlessly. Unfortunately this removal makes images look distorted :( I'am trying to solve the issue by myself but any help would be appreciated.

**Comment by krzyko** [comment]
OK. The problem was solved for me. I've set "defaultImage" option to "null" and this solved my issue.
The case was image css "height" set to "auto" (100% also was problematic) and width set to 100% images container's size. Thus default blank image (1x1 size) was expanded proportionally to 1200x1200 or 2400x2400.
Is there any possibility to mark handled elements with custom class name? With this option it would be easier to apply css styles like automatic height only to loaded elements?

**Comment by eisbehr-** [comment]
Hello @krzyko,

I'm actually on holiday, so this is only a quickquick response:

You can archive this whit the 'afterLoad' callback. Just append the class you want at this point and you should be fine. Or maybe use 'beforeLoad' when you need this before loading the real image.

You will find examples on the project page.

Hope you will be fine with this solution!

**Comment by krzyko** [comment]
Thank You, "afterLoad" callback was the feature I needed. Brilliant idea!
Last thing that remains, is determining "default image" desired height for responsive images (styled with css to auto height and 100% width) without loading real images themselves. Only solution that comes to my mind is calculating desired percentage height by multiplying current percentage width and aspect ratio stored within images' width and height attributes, but maybe there is simpler way to solve this problem.
Anyway, enjoy Your holidays!
