### ISSUE TITLE
Background images with overlays

### ISSUE THREAD

**Issue by XantheStudios** [eisbehr-/jquery.lazy#100]
Hi

On my websites I overlay background images in the following way:
`background-image: linear-gradient(rgba(215, 210, 203, 0.6), rgba(215, 210, 203, 0.6)), url('https://sto.warehouse701.co.uk/v1/assets/imgs/DJI_0062_3_bw.jpg');`, and it works great.

One of my sites as an issue of being slow at the moment so I am looking at implementing Lazy Loading images. I have decided on your plugin because it allows the lazy loading of background images.

Is it possible to apply the overlay in the way I do with your plugin?

Regards

Peter

**Comment by eisbehr-** [comment]
Hello @XantheStudios 

Of course you can. There are different ways to do such custom loading. I made you some examples. Select what matches your case the most. 😉 

### 1. Use `afterLoad` callback to customize the result

With this [callback](https://github.com/eisbehr-/jquery.lazy#callbacks--events) you could manipulate the element after the lazy loading is done.

```JS
$('div').Lazy({
  afterLoad: function(element) {
    var gradient = "linear-gradient(rgba(215, 210, 203, 0.6),rgba(215, 210, 203, 0.6)),";
    var img = element.css("background-image");
    element.css("background-image", gradient + img);
  }
});
```
[Working example.](https://jsfiddle.net/wqc61evh/)


### 2. Use a `custom loader`

A [custom loader](https://github.com/eisbehr-/jquery.lazy#custom-content-loaders) is a way to implement own loaders for Lazy. In this case you do basically an background image loading with a bit different handling.

```JS
$('div').Lazy({
  gradient: function(element, response) {
    var imageObj = $(new Image());

    imageObj.one("error", function() {
      response(false);
    })
    .one("load", function() {
      element.css("background-image", element.css("background-image") + ",url('" + imageObj.attr("src") + "')");
      element.removeAttr("data-loader data-src");
      imageObj.remove();
      response(true);
    });

    imageObj.attr("src", element.attr("data-src") || "");
    imageObj.complete && imageObj.trigger("load");
  }
});
```

[Working example.](https://jsfiddle.net/4o1bp3xv/)


### 3. Use an own plugin

A [plugin](https://github.com/eisbehr-/jquery.lazy/tree/master/plugins#create-an-own-loader-plugin) is pretty similar with the content loader. But if you want to use this own loading (with your gradient) on many sites, this would be a better solution to create a `plugin` instead of a `custom loader`. You can make your loader available on all sites easily.

```JS
// this is the plugin initialization, put this in a file like `lazy.gradient.plugin.js`
// and load this file after the `jquery.lazy.js` or `jquery.lazy.min.js`
(function($) {
    $.Lazy("gradient", function(element, response) {
    var imageObj = $(new Image());

    imageObj.one("error", function() {
      response(false);
    })
    .one("load", function() {
      element.css("background-image", element.css("background-image") + ",url('" + imageObj.attr("src") + "')");
      element.removeAttr("data-loader data-src");
      imageObj.remove();
      response(true);
    });

    imageObj.attr("src", element.attr("data-src") || "");
    imageObj.complete && imageObj.trigger("load");
    });
})(window.jQuery || window.Zepto);

// then you can just initialize lazy anywhere
// note that the '<div>' elements has a `data-loader` attribute with the plugin name
$('div').Lazy();
```

[Working example.](https://jsfiddle.net/2Lnr8h7o/)

**Comment by XantheStudios** [comment]
Hi Eisbehr

Thank you ever so much for these, can’t wait to give them a try.

Regards

Peter Carless | The Admin Team

www.xanthestudios.co.uk <https://www.xanthestudios.co.uk/>
