### ISSUE TITLE
Lazy loading not working properly on IMG element

### ISSUE THREAD

**Issue by SilverFoxA** [eisbehr-/jquery.lazy#108]
Here 's the code

`<img class="lazy" data-src="image">`
Initialised `lazy` on document load

`  $('.lazy').Lazy();`

But the image doesn't show up because the output result still has the attribute `data-src`

`<img class="lazy-loaded" data-src="image" src="image">`

TIA

**Comment by eisbehr-** [comment]
Hello @SilverFoxA 

The `data-src` has nothing to do with the fact that no image is showing. But if your page is really configured like you posted it is impossible to get this kind of output. There might be another problem in your page. So maybe show me the page, or create a jsfiddle with this problem. I would help you then ...

**Comment by SilverFoxA** [comment]
Kindly check the video attached [Screen Recording](https://drive.google.com/open?id=0B0SU7dip441gVjZBYVFYR2toWEk)

The image shows up if the `data-src` attribute is removed.

**Comment by eisbehr-** [comment]
As said before, the `data-src` attribute has **nothing** to do with the fact an image is showing up or not! The `data-src` is completely irrelevant to regular html. If you have an behavior like this, there is possible another problem, or a different library/environment in between, causing this. But this has nothing to do with lazy.

Another hint that Lazy is not involved: normally, after loading, Lazy would remove the `data-src` attribute from the element. But it seems that the image was handled by another script/library, or you have used the config parameter `removeAttributes: false`, what you didn't did, like shown in your first post.

So please create a jsfiddle, recreating your problem when using Lazy and I will see where the problem is. A video doesn't help.

And here is an [example for you](https://jsfiddle.net/f25cbvgb/), showing that `data-src` is completely ignored by normal html.
