### ISSUE TITLE
onFinishedAll event not triggered

### ISSUE THREAD

**Issue by samysadi** [eisbehr-/jquery.lazy#113]
Hello,

I want to point out that the onFinishedAll event is not triggered.

This is not critical issue, as the same result can be achieved using beforeLoad, afterLoad and onError events (by counting the number of submitted images). But, it would be nice, if this was fixed.

Cheers,
Samy.

**Comment by eisbehr-** [comment]
Hello @samysadi 

could you please give me more details about your problem and would you please create a [jsfiddle](https://jsfiddle.net) where I can see the problem in action? Because I don't see any problem with this callback at the moment. Here is an [working example](https://jsfiddle.net/96emf95g/1/).

Thank you!

**Comment by samysadi** [comment]
Thanks for the answer,
I tried to reproduce the issue in jsfiddle (for 2 mins), but it's not happening.
So I just created a small html file, where you can see the issue (try to refresh the page multiple times). 

In the file there is 5 images, but only 4 load lazily. I need this behavior for a carousel (where I need the main image to load with src, and the others to load lazily).

[lazy.html.zip](https://github.com/eisbehr-/jquery.lazy/files/1403133/lazy.html.zip)

**Comment by eisbehr-** [comment]
The problem is, that you use the jQuery selector `'img'`. But the first `img` element has no `data-src` attribute. So Lazy can't load the first image. That's why `onFinishedAll` will not trigger, because you give Lazy 5 images to load, but it only can handle 4 of them. So you need to add the `data-src` to all images and/or use a more decent selector. For example `img[data-src]` or add class like `.lazy`.

**Comment by samysadi** [comment]
Hello eisbehr,

Yes the issue is indeed due to the fact that not all selected items have a data-src.
Shouldn't the plugin handle this and ignore elements without data-src?
Because, technically, if there is nothing to load for a given element, then the plugin's task is finished for it.

As per the documentation, the onFinishedAll event should be triggered after finishing the load tasks (independently if an error happens).

**Comment by eisbehr-** [comment]
Totally agree!

I was a bit confused too, that I've not filtered this out. So I took a look to the code and found a bug, where the filtering was not applied correctly. I fixed this, and within version [1.7.6](https://github.com/eisbehr-/jquery.lazy/releases/tag/1.7.6) the problem should be fixed!

Thank you for reporting!

**Comment by samysadi** [comment]
Thank you for taking the to fix it so quickly :)
