### ISSUE TITLE
Not lazy loading at all

### ISSUE THREAD

**Issue by dbaronov** [eisbehr-/jquery.lazy#120]
Please see the jsfiddle here to see there in no lazy load action there, only fading in all the items at once: https://jsfiddle.net/pxpvb56e/5/ .
Tested in Chrome Version 62.0.3202.94 (Official Build) (64-bit) and Firefox 57.0 (64-bit).

Please advise on how to fix the issue.

**Comment by eisbehr-** [comment]
Sorry, but whats your problem?
Your example works well in Firefox an Chrome.

**Comment by dbaronov** [comment]
It load the images but not in lazy load fasion - all images are loaded in one go.

**Comment by eisbehr-** [comment]
Yes, of course they did, because you don't gave the images a default width and height. 😉 
https://jsfiddle.net/pxpvb56e/6/

**Comment by dbaronov** [comment]
Ahhh, I see now. Can I have make images responsive?

**Comment by eisbehr-** [comment]
Yes, you can use `srcset` and `sizes` attributes or if you just want retina images, use `data-retina`.

http://jquery.eisbehr.de/lazy/example_use-srcset-and-sizes
http://jquery.eisbehr.de/lazy/example_retina-image-support

**Comment by dbaronov** [comment]
I have seen the above links, but images there are not responsive, they simply get squashed vertically and do not maintain the aspect ratio.

**Comment by eisbehr-** [comment]
That belongs to your implementation. That is no technique I invented, it's a standard. ;)
Good luck!

**Comment by dbaronov** [comment]
The behaviour I have described (images get squashed) is actually on your website demo pages.

**Comment by dbaronov** [comment]
Update:

Looks like I have managed to find the solution: https://jsfiddle.net/9nL7z8s6/1/ .

Could you have a look and conform you get the same result and images are resizing and maintaining their aspect ratio.

**Comment by dbaronov** [comment]
The behaviour is very inconsistent. Sometimes works well another just loads all images at once. Puzzled.

**Comment by eisbehr-** [comment]
Your solution only work if the images are in browser cache already, because the browser can't know what `100%` is, when the image was not loaded yet.

**Comment by dbaronov** [comment]
Agree, but otherwise images are not responsive and aspect ration is breaking. What would be the solution?

**Comment by eisbehr-** [comment]
The problem in this case is the lazy loading. Normal image tags with the implementation of responsiveness would work. But whenever javascript is in between there would be a such problems. There are two possible ways to get it working:

1.) Tell the browser the correct width/height of each image.

2.) Work with min-width and min-height. You need default values for lazy load to work. Otherwise images would have 0x0 pixel size and would work all at once again. The only downside here is, that the lazy loading threshold is a bit inaccurate, when min-height and real height is to far away from each other. Then lazy would load content a bit to early. But that is okay in the most cases ...

**Comment by dbaronov** [comment]
Following your advise I have experimented and have got much more reliable solution: https://jsfiddle.net/9nL7z8s6/3/ .

I think it works pretty well. You might want to describe this case on your website. This will make your plugin much more attractive.

Thank you for your time.
