### ISSUE TITLE
Images lazy loading issue within carousel

### ISSUE THREAD

**Issue by vishy93** [eisbehr-/jquery.lazy#140]
Hi Guys,

I have come across a weird issue, incorporating the lazy loader to lazy load my jcarousel images. It will lazy load images not even in view yet, even though I have set `visibleOnly: true`. 

Looking at the networks tab in chrome I can see 7 images from the carousel being loaded, even though the carousel is not in view. It is 500px give or take below. I have a 500~px slideshow at top. I have also defined `threshold: 250` to try and make it only load upto 250px below.
 
Moreover, It will not lazy load some images untill I scroll on the page.

To demonstrate, I have quickly constructed a [codepen](https://codepen.io/vishpatel93/pen/EEZBXw/) 

Note:- In Codepen, click prev button on carousel, and you should hopefully see three images showing that they are not loading.

**Comment by eisbehr-** [comment]
Hello @vishy93 

This is not an issue, you just used it wrong. You need to tell Lazy, that you changed the view, because you don't use normal `scroll` events in a slider. Just as quick example, I edited the codepen. Please take a look and update it for your needs.

https://codepen.io/anon/pen/wmJvGL?editors=0010

**Comment by vishy93** [comment]
I have tested your solution and it does make the images work now on scroll. Bizarrely, although it wasn't when I tested locally. On page load the images won't load until I scroll page or carousel. Am I okay to send you an updated codepen?
