### ISSUE TITLE
Placeholder does not work

### ISSUE THREAD

**Issue by SPQRInc** [eisbehr-/jquery.lazy#145]
Hi everybody,

I am using `jquery-lazy` and I am still trying to implement the placeholder. This is my `Lazy` init:

```
$(function($) {
    $('img.lazy').Lazy({
        effect: 'show',
        effectTime: 100,
        visibleOnly: true,
        scrollDirection: 'both',
        combined: true,
        placeholder: 'data:image/gif;base64,R0lGODlh...kEvTBUlARdkEubeCIUAZQqBQQAOw=='
    });
});
```

But if I scroll down, there is no loading image shown - just the images are being loaded.

**Comment by eisbehr-** [comment]
Hello @SPQRInc 

are you loading images or containers? If images, you need to use `defaultImage` instead of `placeholder`. Here is a[ working example](https://jsfiddle.net/g0scbds8/).

Another hint, it's better to maintain a loading image with css, [like this](https://jsfiddle.net/g0scbds8/2/). This makes it more easy to handle in the future. And if possible, use a image file instead of a base64 string. You could even set the image file as default `src` to your `img` elements.
