### ISSUE TITLE
refresh image src after changing data-src via jquery

### ISSUE THREAD

**Issue by leonardtoh** [eisbehr-/jquery.lazy#158]
Hi,

How do i force it to refresh the image src after i change the data-src attribute via script? eg.

`$(this.getElement()).find("img").show().attr("data-src", newImageUrl);`

The image element is still showing the old image src even though the data-src was changed.

Thanks.

**Comment by eisbehr-** [comment]
The `data-src` ist an attribute, just used by Lazy to load the image. If you changed the `data-src` before Lazy has loaded the image, you have nothing to do, then Lazy would use the new value on load.

But if you change the `data-src` after Lazy already handled the image, it has no effect. After Lazy has loaded an element, it will be removed from the queue. So if you change an image afterwards, you should better set the `src` directly instead of `data-src`. Everything else would not make sense ...
