### ISSUE TITLE
No loading of images when using appendScroll in non-visible area

### ISSUE THREAD

**Issue by 4BRobby** [eisbehr-/jquery.lazy#164]
Reproduction:
- Use page http://jquery.eisbehr.de/lazy/example_elements-inside-a-container
- Switch for example to mobile view in Chrome
- Load page with position most top (just press enter to reload page
- Because images are outside of visible area it seems that initial loading is not fired
- But when scrolling to this section the images are also not loaded

Fix would be to have appendScroll not fire scrolling only for the container it is attached but still keep the event handler for window scroll event.

**Comment by 4BRobby** [comment]
Workaround:
`scrollableContainer = $(".scrollableContainer");
scrollableContainer.find(".lazy").Lazy({
  appendScroll: scrollableContainer.add($(window))
});`

**Comment by eisbehr-** [comment]
Interesting. Yes, that is truly a limitation. No idea right now how to genuine fix this issue. I will leave this open. Thank you for the feedback.

**Comment by Okipa** [comment]
Hi there, I have a side-menu with lazy image on it and the behaviour is very weird.  
It would be cool if we could have a `refresh` method in order to tell to the library to check again in the given element if some image have not been lazy-loaded.  
I tried the workaround above and the `afterLoad` event is never triggered.

**Comment by eisbehr-** [comment]
The behavior is not wrong @Okipa . Lazy only listens to scroll events by default, so opening a menu is not detected in any way by Lazy. That's nothing wrong, it's just how it should be. You need to tell Lazy if you updated the viewport in any way.

And there is a bunch of [public functions](https://github.com/eisbehr-/jquery.lazy#instances-and-public-functions) to control Lazy and load images you put in viewport. In this case, it's called `update` instead of `refresh`. ;)
