### ISSUE TITLE
Momentary broken image when alt attribute is set

### ISSUE THREAD

**Issue by ApplicationError** [eisbehr-/jquery.lazy#182]
A broken image is shown for a second or so, before the image is loaded, but only if the IMG has an alt attribute.

**Comment by eisbehr-** [comment]
Hello @ApplicationError 

This might because you didn't set a default image to the `src`. Lazy will do this for you too, but there might be situations where such broken images would be shown.

To solve that, just add a small 1x1px transparent gif or png to it as default. This will remove the broken images.

**Comment by ApplicationError** [comment]
Adding the transparent 1x1 gif to the src works. Thanks for the workaround.
