### ISSUE TITLE
Loading image using css

### ISSUE THREAD

**Issue by Redani** [eisbehr-/jquery.lazy#24]
Hi Eisbehr and Thanks for this nice plugin :)
I'm trying to use it but i'll have 2 questions please:
1- regarding the loading image, I'm currently using a css generated image (-webkit-animation) and was wondering how i can integrate it with your plugin.

2- i have read that using lazy loader, will prevent google from indexing images, is that true? if yes, is there an alternative?

Thanks in advance
Cheers

**Comment by eisbehr-** [comment]
Hello @Redani,

well, css loaders are a bit more complicated. I would put the loader behind the images itself. So the image will stay before the loader when its finally loaded. If you like you could even remove the loader after loading, e.g. with the `afterLoad` callback.

I'll never think about the indexing of images, because i would like my content will be indexed, not my images. But maybe you could do something in the onload event and change the dom there. Or maybe make use of the `noscript` tag? Actually i don't have a tested answer for you. :)

Daniel

**Comment by Redani** [comment]
Thank you very much for your prompt reply :)

OK, i'll give it a try soon and will let you know ;)

Yes, i've seen that workaround using noscript, but i ddn't like it th
Have a great day
