### ISSUE TITLE
All images load at once

### ISSUE THREAD

**Issue by fonzerelly** [eisbehr-/jquery.lazy#248]
Hi Daniel,
I tried to rebuild your basic usage example: 

``` html
<html>
    <style>
        div.lazy {
    max-width: 700px;
    height: 467px;
    display: block;
    margin: 30px auto 0;
    font-weight: 700;
    font-size: 20px;
    position: relative
        }
    </style>
    <body>
        <h1>test</h1>
        <div class="lazy" style="display:block; background-image:url('a.png');" data-src="0.jpg">Beispieldiv</div>
        <div class="lazy" style="display:block; background-image:url('a.png');" data-src="1.jpg">Beispieldiv</div>
        <div class="lazy" style="display:block; background-image:url('a.png');" data-src="2.jpg">Beispieldiv</div>
        <div class="lazy" style="display:block; background-image:url('a.png');" data-src="3.jpg">Beispieldiv</div>
        <div class="lazy" style="display:block; background-image:url('a.png');" data-src="4.jpg">Beispieldiv</div>
        <div class="lazy" style="display:block; background-image:url('a.png');" data-src="5.jpg">Beispieldiv</div>
        <div class="lazy" style="display:block; background-image:url('a.png');" data-src="6.jpg">Beispieldiv</div>
        <div class="lazy" style="display:block; background-image:url('a.png');" data-src="7.jpg">Beispieldiv</div>
        <div class="lazy" style="display:block; background-image:url('a.png');" data-src="8.jpg">Beispieldiv</div>
        <div class="lazy" style="display:block; background-image:url('a.png');" data-src="9.jpg">Beispieldiv</div>
        <script src="node_modules/jquery/dist/jquery.js"></script>
        <script src="node_modules/jquery-lazy/jquery.lazy.js"></script>
        <script>
            jQuery('h1').text('aktiv')
            jQuery('.lazy').Lazy({
                beforeLoad: (e) => {
                    console.log('## about to load ' + e.data('src') + (new Date()).toISOString())
                },
                afterLoad: (e) => {
                    console.log('## finished to load ' + e.data('src') + (new Date()).toISOString())
                },
                onError: (e) => {
                    console.log('##############', e)
                },
                onFinishedAll: () => {
                    console.log('############### done')
                }
            })
        </script>
        
    </body>
</html>
```

But when you look at the output, you'll see, that all my images get load at once and not one by one when the user scralls down:
``` sh
## about to load 0.jpg2021-06-17T10:35:13.066Z
(index):31 ## about to load 1.jpg2021-06-17T10:35:13.067Z
(index):31 ## about to load 2.jpg2021-06-17T10:35:13.067Z
(index):31 ## about to load 3.jpg2021-06-17T10:35:13.068Z
(index):31 ## about to load 4.jpg2021-06-17T10:35:13.068Z
(index):31 ## about to load 5.jpg2021-06-17T10:35:13.069Z
(index):31 ## about to load 6.jpg2021-06-17T10:35:13.070Z
(index):31 ## about to load 7.jpg2021-06-17T10:35:13.070Z
(index):31 ## about to load 8.jpg2021-06-17T10:35:13.071Z
(index):31 ## about to load 9.jpg2021-06-17T10:35:13.071Z
(index):34 ## finished to load 1.jpg2021-06-17T10:35:13.143Z
(index):34 ## finished to load 0.jpg2021-06-17T10:35:13.146Z
(index):34 ## finished to load 2.jpg2021-06-17T10:35:13.150Z
(index):34 ## finished to load 3.jpg2021-06-17T10:35:13.153Z
(index):34 ## finished to load 4.jpg2021-06-17T10:35:13.157Z
(index):34 ## finished to load 5.jpg2021-06-17T10:35:13.160Z
favicon.ico:1 GET http://localhost:5000/favicon.ico 404 (Not Found)
(index):34 ## finished to load 6.jpg2021-06-17T10:35:13.173Z
(index):34 ## finished to load 7.jpg2021-06-17T10:35:13.176Z
(index):34 ## finished to load 9.jpg2021-06-17T10:35:13.178Z
(index):34 ## finished to load 8.jpg2021-06-17T10:35:13.181Z
(index):40 ############### done
```

Expected _Behaviour:
``` sh
(index):31 ## about to load 0.jpg2021-06-17T10:35:13.066Z
(index):31 ## about to load 1.jpg2021-06-17T10:35:13.067Z
(index):31 ## about to load 2.jpg2021-06-17T10:35:13.067Z
(index):34 ## finished to load 1.jpg2021-06-17T10:35:13.143Z
(index):34 ## finished to load 0.jpg2021-06-17T10:35:13.146Z
(index):34 ## finished to load 2.jpg2021-06-17T10:35:13.146Z
## about to load 3.jpg2021-06-17T10:35:13.068Z
## finished to load 3.jpg2021-06-17T10:35:13.153Z
## about to load 4.jpg2021-06-17T10:35:13.068Z
## finished to load 4.jpg2021-06-17T10:35:13.157Z
...
```

What am I doing wrong? Do I have to configer something differently?

Thanx for your help
fonzy

**Comment by elderferreiras** [comment]
This could have something to do with your version of jQuery.

The website with the examples that work uses jQuery `1.11.1`. As of jQuery's 1.8, the `height()` function gets the height of the page plus the scrollbars, which means when the function `_getActualHeight` inside the library is called, but it returns the entire height of the page, not only the viewable part of the page. 

This results in all the images loading because when the function `_isInLoadableArea` is called, it thinks that all the images are in the loadable area.

Locally, when I changed the two functions, `_getActualWidth`, and `_getActualHeight`, to use `window.innerWidth` and `window.innerHeight` instead of `$(window).width()` and `$(window).height()`, the lazy loading worked.

**Comment by elderferreiras** [comment]
You should check if you have `<!DOCTYPE HTML>` at the beginning of your HTML page. This change worked for me.

**Comment by fonzerelly** [comment]
That did it - thanx a lot. Why does this tiny detail has such an impact?

**Comment by dkern** [comment]
Because missing doctype is invalid html. 
;)

**Comment by elderferreiras** [comment]
@fonzerelly The browser enters `Quirks mode` without a doctype.

jQuery does not work well in `quirks mode`. From the [blog release on jQuery 1.8.1](https://blog.jquery.com/2012/08/30/jquery-1-8-1-released/):

> Don’t use Quirks mode! jQuery has never supported Quirks mode and we do not perform any testing in Quirks. This can affect values like $("window").height(), and the jQuery 1.8 Quirks mode results did change in order to support some modern browser features.

That's the answer for you.

This library uses `$("window").height()` to calculate the height of the viewable area and to determine if the other images below the viewable area should be loaded or not. In quirks mode, `$("window").height()` will return the height of the viewable area + scrollable area instead of only the viewable area. Because of the former, all the images will be considered to be within the viewing area and therefore they will all be loaded.

[This is the specific code ](https://github.com/dkern/jquery.lazy/blob/master/jquery.lazy.js#L565)in this library that uses `$("window").height()` and that will cause the odd behavior you came across if quirks mode is on.
