### ISSUE TITLE
Defer the lazy loading

### ISSUE THREAD

**Issue by tgowing** [eisbehr-/jquery.lazy#263]
We are using the jquery.lazy plugin on the website and we have a structure like this:

```
[WELCOME]
[VIDEOS]
[...]
[BOOKS]
[FOOTER]
```

Depending on the navigation, we may want to call a scroll to [BOOKS] (the bottom section). Because the browser scrolls down through all the previous sections ([VIDEOS] etc), they will get loaded. But we don't want them to be loaded unless the user keeps them in the viewport for `x` ms. So, if the user scrolls past any [SECTION] of the page quicker than than the configured defer ms value we don't want that [SECTION] to load. IS that possible?

From the documentation we are unsure if that is already possible with `throttle`, but it doesn't seem to work anyway...

Any feedback would be greatly appreciated.
Thank you!

/cc @ionicabizau

**Comment by dkern** [comment]
I have no out-of-the-box solution for this specific case. Some Ideas that could be worth trying:

- Do you use `scroll` to go to this sections? If possible don't use scroll, instead set the page coordinates from top. This should not trigger lazy, because this is not a scroll event I think.

- Initialize the Lazy instances for each content type only when the user is staying there for a amount of time. This may only solve the problem for the first time scrolling to a part of the page, but maybe already help.

- Create a custom loader for lazy and use a globale variable to disable loading while transition. Example:

```js
let loadEnabled = true;

$(".lazy").Lazy({
  customLoaderName: function(element) {
    if (loadEnabled) {
      // load content ...
    }
  }
});

function goToConent() {
  loadEnabled = false;
  // scroll to elements ...
  loadEnabled = true;
}
```

I think overall you need to think a bit outside the box here. ;) Good luck.
