### ISSUE TITLE
Error at _isInLoadableArea function

### ISSUE THREAD

**Issue by standus** [eisbehr-/jquery.lazy#34]
I have unspecified errors in IE8 mode in IE11 at line:
var elementBound = element.getBoundingClientRect();
in function: function _isInLoadableArea(element)

I resolved it with code:
var elementBound = null;
            try {
               elementBound = element.getBoundingClientRect();
            } catch(e) {
               elementBound = { top : element.offsetTop, left : element.offsetLeft };
            };

Can you update your source?

**Comment by eisbehr-** [comment]
Hello @standus

Thank you for your feedback. Please give me some time to check this. I'm never got such errors. Which jquery version are you using? Did you get an example / fiddle where I can reproduce the error?

**Comment by standus** [comment]
It was with jQuery 2.x, but in mative IE8 I used jQuery 1.x.

**Comment by eisbehr-** [comment]
Could you please give me the subversion of your jquery version used in IE8 mode? It made some differences. Thanks!

**Comment by eisbehr-** [comment]
Actually I cant reproduce it. But I'm on a mac, so i have to test it within this week. ;) But the `getBoundingClientRect` is supported by IE8 as well. I think this is an problim with the emulution of IE8.

http://caniuse.com/#feat=getboundingclientrect

**Comment by standus** [comment]
v2.1.4 + jQuery Migrate v1.2.1

**Comment by eisbehr-** [comment]
I'm not 100% sure, but jQuery 2.1.4 is not compatible with IE8. jQuery migrate only adds support for old code and functions, but doesn't add support for IE8. Please correct me if I'm wrong ...

**Comment by standus** [comment]
Ohh sorry, you are right.

**Comment by eisbehr-** [comment]
No problem. Please let me know if changing the jQuery version to 1.9.1 on IE8 mode will fix your problems. Thanks!

**Comment by eisbehr-** [comment]
Well, seems to be done ...

**Comment by ffaubert** [comment]
FYI: This is not an invalid issue.  IE 11 **will** throw an exception on getBoundingClientRect if it is called on a detached element, which then stops Lazy for working for all remaining elements.  

See [this](https://connect.microsoft.com/IE/feedback/details/829392/calling-getboundingclientrect-on-an-html-element-that-has-not-been-added-to-the-dom-causes-unspecified-error) and [this](http://jsfiddle.net/jonathansampson/3vqddemh/) for reference.

**Comment by eisbehr-** [comment]
> IE 11 will throw an exception on getBoundingClientRect if it is called on a detached element

Totally correct. But we're not talking about detached elements. The `getBoundingClientRect` is only used for elements inside the document context. Everything else for an image loading operation would not make sense. So this shuld not be a problem at all in this case.

But you're right. It could be a usecase problem, when registering jQuery on wrong elements. But that is not as easy as it sounds. 😉

**Comment by ffaubert** [comment]
The original incident was not talking about detached elements, but I had this happen to me with detached elements, searched your issue database and found this ticket.  In my particular use case I have a homepage with a bunch of image carousels on them (think like the Netflix main screen).  Anything on the screen has been loaded by Lazy, but there will still be other images in each carousel that are offscreen and have not been loaded yet.  I went to refresh the contents of my carousel from the server, and started getting these errors in IE because Lazy was still hanging onto objects that had been detached from the DOM.  The error completely broke Lazy and it failed to load any further objects.  So I thought I'd add to this ticket with a way of how it can happen.

I worked around this by manually removing the contents of that carousel from Lazy before filling it with new content, to avoid Lazy hanging on to detached elements -- which is a better solution for memory reasons anyway.  But that wasn't exactly straightforward either as there is no public API to remove items from Lazy.  I wound up having to set data-loaded to true on each of them and then call getItems() to trigger an internal cleanup.

**Comment by eisbehr-** [comment]
Interesting usecase, thank you for your report. It's nice to know. Maybe I should add some checks, if the element is still inside the document. Everything else is useless for Lazy anyway.

Some thougs to your workaround:

As you said, the best way is to use a fresh instance whenever you update your content. I would suggest to use `.destroy()` public function. Maybe wrapped in a function you can call on start and every update to re-initialize Lazy. Just a quick sketch below, how it could work ...

```JS
function initLazy() {
    window.lazy && window.lazy.destroy();

    window.lazy = $('.lazy').lazy({
        afterLoad: function(elem) {
            elem.removeClass('lazy');
        }
    });
}
```

**Comment by nguyenlamzx** [comment]
@eisbehr- 
please help me to check my PR for fix this issue.
Thanks,
