### ISSUE TITLE
Image/Text Overlap

### ISSUE THREAD

**Issue by Riz0** [eisbehr-/jquery.lazy#38]
Hello,

I'm having a bit of an issue with images and text overlapping in IE (works fine in other browsers) when using this plugin. It doesn't always happen maybe 1/5 page loads this will occur. You can see how it looks here: http://screencast.com/t/grzRP19z7

This is the how lazy is called:
```
        $mt("img.lazy").lazy({
            bind: 'event',
            effect: "fadeIn",
            effectTime: 800,
            threshold: 50,
        });
```
So I changed the parameters like so:
```
        $mt("img.lazy").lazy({
            bind: 'event',
            effect: "fadeIn",
            effectTime: 0,
            threshold: 0,
        });
```

And now it initially overlaps, but re-adjusts properly after a bit of scrolling like so: http://screencast.com/t/yFqtykAldu4

I'm using default configs:
```
var configuration =
        {
            // general
            bind            : "load",
            threshold       : 500,
            fallbackHeight  : 2000,
            visibleOnly     : true,
            appendScroll    : window,

            // delay
            delay           : -1,
            combined        : false,

            // attribute
            attribute       : "data-src",
            retina       : "data-srcX2",
            removeAttribute : true,

            // effect
            effect          : "show",
            effectTime      : 0,

            // throttle
            enableThrottle  : false,
            throttle        : 250,

            // callback
            beforeLoad      : null,
            onLoad          : null,
            afterLoad       : null,
            onError         : null
        };
```

Is there any thing I should try changing  to remedy this? I'm not very skilled with jquery, but I tried playing around with it to no avail. Thanks in advance.

**Comment by eisbehr-** [comment]
Hello @Riz0 and thank you for contacting me!

But I'm not really sure how to solve this problem. It's hard because I'm not know any of your html and css. But I'm pretty much sure, that this is a problem with your layout and not a problem with this plugin. I think Lazy only triggers it.

Some first ideas:
- do you set a correct width / height for your images?
- do you set correct width / height for the outer product box?
- do you float elements? If so, do you correctly clear them?

The problem could be occur becaus of missing some of these kind of definitions. Then IE is rendering the page with wrong informations and when Lazy loads the images the content will break and overlap. But as said before, this is not a plugin problem, it's only the trigger ...

And why are you using `bind: 'event'`? Are you using an event to start loading? I didn't see anything in the videos. If you want to do it after page load use `bind: 'load'` (it's default too).

Good luck!

**Comment by Riz0** [comment]
Thanks very much for the well thought response. Your intuition above specifying height for the product box was right.  I assumed since I was using a grid system it would be set dynamically. But for whatever reason IE wasn't being agreeable. Thanks again

**Comment by Riz0** [comment]
Hiya @eisbehr- 

I hate to bug you again, but I'm experiencing another little issue with images only loading after a scroll. It doesn't always happen, but when it does it look like this: http://screencast.com/t/z396Y2klSuo

My settings are the same as above. I tried changing bind to 'load' (that stopped loading images all together) and upgrading to current version of master but it doesn't seem to help. This it the version of the loader I'm currently running : https://dpaste.de/Mtmk

Any thoughts on how to approach this? 

Thanks again

**Comment by eisbehr-** [comment]
Hello @Riz0 

wow, you use version 0.1.15. It's about 2 years old. Would recommend to switsch to 0.6.4!
Could you try it again with this version? If it's not working please paste me your config again and tell me witch jQuery version you are using.

Thanks!

**Comment by Riz0** [comment]
Alright, I switched again to version 0.6.4 (default, no changes) from master and I using the following to call the loader:

---
        $mt("img.lazy").lazy({
            bind: 'event',
            effect: "fadeIn",
            effectTime: 0,
            threshold: 0,
---

My jQuery version is v1.11.2. It still has the issue, starts to load after a small scroll. I tried to change bind to load as you mentioned but that stops loading all together. 

Thanks again for any advice

**Comment by eisbehr-** [comment]
You really need to set `bind: 'load'`, because it causes problems, when you start using lazy and the DOM is not ready! And speaking of this, do you put your Lazy initialization in a jQuery ready state? Like:
```JS
$(function() { /* init here */ });
```

And what do you mean with `that stops loading all together`? Do you want to load the images just in the viewport, or do you want to load ALL images after the page loades(delayed loading)?

For only loading the images in view (lazy loading) you should use a default config. For loading everything after page load you have to use a delay:
```JS
$mt("img.lazy").lazy({
        delay: 0,
        effect: "fadeIn",
        effectTime: 0
});
```

**Comment by Riz0** [comment]
I mean that the images just won't display at all with bind: 'load', you can see me updating it on then off here live: http://screencast.com/t/DgNGNBoCk

I believe  it is in a jquery ready state, please correct me if I an wrong. I am still learning the syntax. Here is the full snippet that loads on the page: 

---
           $mt(document).ready(function () {
            $mt("[rel=tooltip]").tooltip();
        });
        $mt("img.lazy").lazy({
            bind: 'event',
            effect: "fadeIn",
            effectTime: 0,
            threshold: 0,
        });
---
Ideally, I'd like to load the images just in the viewport as it is less resource intensive. I also tried adding the  delay: 0 just to test it out, but that didn't remedy it either.Any other thoughts? Thanks again

**Comment by eisbehr-** [comment]
No, it's not inside. Do it this way:

```JS
// $mt(function() {}); is a shorthand for $mt(document).ready(function() {});
$mt(function ($) {
    $("[rel=tooltip]").tooltip();

    $("img.lazy").lazy({
        effect: "fadeIn",
        effectTime: 0,
        threshold: 0,
    });
});
```

**Comment by eisbehr-** [comment]
I'll close this here again. Feel free to reply anyway!
