### ISSUE TITLE
Ajax load

### ISSUE THREAD

**Issue by AVSYS-AK** [eisbehr-/jquery.lazy#39]
Hi,

great plugin you have developed... 

I am using this in one page app, where i get new images on request. First page load, images do lazy load but when i get new response, the images are no not displayed... 

i have tried following, nothing works

var instance = $('.lazy').lazy();
instance.update();

No images shown after ajax response..  ..can you help ?

**Comment by eisbehr-** [comment]
Hi,

well, your code is not completly correct. First of all, to get the instance this way, you have to set the `chainable` parameter:
```JS
var instance = $('.lazy').lazy({chainable: false});
```

Next you had to add the new element to Lazy. New elements will not automatically add to jQuery/Lazy. You have to do it manually. You can use `addItems` function for this.
```JS
instance.addItems('.lazy');
```

Afterwads you can do an update, but this is optionally. They will otherwise gets loaded when next scroll / resize appears. But you can do it as you wrote:
```JS
instance.update(true);
```

If you handle big amounts of images, you should think about a more uniqe selector each request, if the images are all on one page. Because the `.lazy` selector will get you all images every time again. At least you should remove the class after loading the image then, like:
```JS
var instance = $('.lazy').lazy({
    chainable: false,
    afterLoad: function(element) {
        element.removeClass("lazy");
    }
});
```

But if you remove the old images in your single page app and load completly new images every time, you should destroy the old lazy instance and create a new one. Otherwise the old elements will remain in the instance and could slow down your page over time / many images. You could do it like this:
```JS
$(function($) {
    var instance;

    function registerLazy() {
        if( instance )
            instance.destroy();

        instance = $('.lazy').lazy({
            chainable: false,
            afterLoad: function(element) {
                element.removeClass('lazy');
            }
        });
    }

    function loadNewImages() {
        // do your ajax request / page changes here

        // afterwards renew your Lazy instance
        registerLazy();
    }
});
```

Hope this will help you! :smiley:

Greets,
Daniel

**Comment by AVSYS-AK** [comment]
Thanks for the quick answer. try this now :D

**Comment by ipetrov87** [comment]
Hi!
Thank you for detailed answer @eisbehr- !
 I have been used you great plugin with a Ajax loaded images. I have been use this code:

> But if you remove the old images in your single page app and load completly new images every time, you should destroy the old lazy instance and create a new one. Otherwise the old elements will remain in the instance and could slow down your page over time / many images. You could do it like this:

```
$(function($) {
    var instance;

    function registerLazy() {
        if( instance )
            instance.destroy();

        instance = $('.lazy').lazy({
            chainable: false,
            afterLoad: function(element) {
                element.removeClass('lazy');
            }
        });
    }

    function loadNewImages() {
        // do your ajax request / page changes here

        // afterwards renew your Lazy instance
        registerLazy();
    }
});
```

But I have still not load Ajax images. Spending 2 days to figured out why and making my boss mad because of delaying project i found that the solution is just to add a `bind: "event"` to configuration and now everything work perfect. So here it is my updated code:
```
$(function($) {
    var instance;

    function registerLazy() {
        if( instance )
            instance.destroy();

        instance = $('.lazy').lazy({
            chainable: false,
            bind: "event",
            afterLoad: function(element) {
                element.removeClass('lazy');
            }
        });
    }

    function loadNewImages() {
        // do your ajax request / page changes here

        // afterwards renew your Lazy instance
        registerLazy();
    }
});
```

**Comment by eisbehr-** [comment]
Ohh yes, right. I forgot this parameter there. I'm glad it worked now for you! :wink:
