### ISSUE TITLE
Using deprecated jQuery.error() method

### ISSUE THREAD

**Issue by h6ah4i** [eisbehr-/jquery.lazy#56]
Hi. I noticed that this plugin is using the [`jQuery.error()`](https://api.jquery.com/error/) method which is deprecated since jQuery v1.8. 

Here is a capture of the Chrome's console window. jquery-migrate plugin informs a deprecation notice.

![image](https://cloud.githubusercontent.com/assets/2552365/16824520/74221d82-49a7-11e6-9733-97ba3acd0e2a.png)

I found this issue with the following setup;

- jquery v3.1.0
- jquery-migrate v3.0.0
- jquery v1.7.1

Thanks.

**Comment by eisbehr-** [comment]
Hello @h6ah4i,

thanks for your hint. I've changed everything because of this, but you're right, I forgot one in [line 412](https://github.com/eisbehr-/jquery.lazy/blob/master/jquery.lazy.js#L412). :wink: I will fix this within the next release. This line is only used by custom loaders and plugins. The normal image loading is not affected.

**Comment by h6ah4i** [comment]
@eisbehr- Thanks for your very quick response :)  I am looking forward to the next release!

**Comment by eisbehr-** [comment]
This problem should be fixed as of version 1.7.2.
