### ISSUE TITLE
allow optional throttling with loadAll() 

### ISSUE THREAD

**Issue by zspitzer** [eisbehr-/jquery.lazy#67]
loadAll() doesn't use throttle, add a boolean option to allow using throttle with loadAll()

**Comment by eisbehr-** [comment]
Hi @zspitzer,

well, a throttle makes not really sense to me for this function. First of all, `loadAll` should be called, as the name said, to load all. So basically there is no further action after calling this method. It would causing problems, when this function would run into the throttle and not be executed.

On the other hand, calling this function by default means, that the Lazy instance will be destroyed afterwards. So there would be even errors when calling it again. Or, if `autoDestroy` is `false`, the call of `loadAll` would just be ignored, because Lazy would check if elements where left in this instance.

So, I don't see a use case for this option, it would just be an unnecessaryoverhead.
