### ISSUE TITLE
Issue with horizontal sliders

### ISSUE THREAD

**Issue by softnic** [eisbehr-/jquery.lazy#68]
Not Loading the images which are off the screen horizontally.

I want to load all images which are placed horizontal row. 

May be It have any quick fix. 

![capture](https://cloud.githubusercontent.com/assets/3215571/20559153/1164d5a8-b195-11e6-95b5-3eead7139358.PNG)

**Comment by eisbehr-** [comment]
Hello @softnic,

I think the problem is a wrong useage of the plugin. Lazy will load images initial on page load, and then on `scroll` events. But a slider don't use `scroll`. So the plugin wouldn't know that he has to load something.

So one way would be to use the public function `.update()` of Lazy. Whenever the slider slides in a new image, it has to call this function, to tell Lazy that possible new images are on the screen.

I hope you get what I want to tell you. 😉

**Comment by softnic** [comment]
Thanks :)
