### ISSUE TITLE
Error in basic demo

### ISSUE THREAD

**Issue by microdesign** [eisbehr-/jquery.lazy#75]
I just add your script 

HTML:

`<img class="lazy" data-src="<?php echo $product['thumb']; ?>"   />`

JS 

```
<script type="text/javascript">
  $(function() {
        $('.lazy').Lazy();
    });
</script>
```

Result in console:

Uncaught TypeError: Cannot read property 'attr' of undefined
    at _handleItem (jquery.lazy.min.js:485)
    at _lazyLoadItems (jquery.lazy.min.js:347)
    at _initialize (jquery.lazy.min.js:236)
    at dispatch (jquery-all.js:3)
    at i (jquery-all.js:3)

Any ideas how I can solve this?

**Comment by eisbehr-** [comment]
Hello @microdesign,

did you checked your html output as well? Because `<?php echo $product['thumb']; ?>` may be have an error or something. Check your output and retry. In general, nothing is wrong on the shown here.

If the problem remains, please create a js fiddle reproducing the problem. I will find the problem then! ;)

**Comment by microdesign** [comment]
Website is working one and images are there:

the images was just: 

`<img src="<?php echo $product['thumb']; ?>" />`

and I change them to 

`<img class="lazy" data-src="<?php echo $product['thumb']; ?>" />`


So yes images are loaded.

**Comment by eisbehr-** [comment]
Okay, then please create a [jsfiddle](https://jsfiddle.net) recreating the problem. I will investigate on this then ...

**Comment by eisbehr-** [comment]
Closed because of missing fedback.
