### ISSUE TITLE
Can I define css background url in css class or only "data-src" option is available?

### ISSUE THREAD

**Issue by jasomdotnet** [eisbehr-/jquery.lazy#80]
Hi, ones again, thank you for a fast answer on #78. 

I have many frames per page: divs with defined `background-image` using CSS and positioned with `background-position`. 20 ~ 100 frames per picture and approx. 10 pictures per page. 

**The problem:**

If I define image source using "data-src" for each frame it will significantly increase the source code.

**The question:**

Is it possible to define `background image` using css `class` similar to this: https://codepen.io/the_ruther4d/pen/aEGAJ (I was not able to run this `codepen.io` demo on my site too and thus I found `jquery.lazy`  :-)

**Comment by eisbehr-** [comment]
This is sadly not possible, because not all browser would support a custom css-attribute I could read in. Two ideas to improve your code:

# 1.) Use `imageBase` configuration property:
If you images all have a base path, you could use `imageBase` to reduce your code. For example:

```HTML
<div class="lazy" data-src="path/to/my/images/img1.jpg"></div>
<div class="lazy" data-src="path/to/my/images/img2.jpg"></div>
<div class="lazy" data-src="path/to/my/images/img3.jpg"></div>
<!-- ... -->
<script type="text/javascript">
$('div.lazy').Lazy();
</script>
```

Would become:

```HTML
<div class="lazy" data-src="img1.jpg"></div>
<div class="lazy" data-src="img2.jpg"></div>
<div class="lazy" data-src="img3.jpg"></div>
<!-- ... -->
<script type="text/javascript">
$('div.lazy').Lazy({
    imageBase: "path/to/my/images/"
});
</script>
```

# 2.) Write an custom loader

If you don't need every functionallity of Lazy you could write yourself a custom loader. This loader would not load the images for you, instead it only set css classes for you. Then your CSS approach would work too. Short example:

```HTML
<div class="lazy" data-loader="cls"></div>
<div class="lazy" data-loader="cls"></div>
<div class="lazy" data-loader="cls"></div>
<!-- ... -->
<script type="text/javascript">
$("div.lazy").Lazy({
    cls: function(element, response) {
        element.addClass("loaded");
        response(true);
    }
});
```

You can found more information about custom loaders on the [project page](http://jquery.eisbehr.de/lazy/example_use-custom-loaders).

**Comment by jasomdotnet** [comment]
1. Thanks for hints

2. I tested 2nd one but it doesn't work:

http://pastebin.com/meGYEpk5

**Comment by eisbehr-** [comment]
Of course you would need to change your CSS Structure a bit. Think about what `.loaded:nth-of-type` does and what the custom loader will do. At start there is no element with `.loaded` class and then ist counts up. So you need to set the `nth` to an always existing class and let this only apply when `.loaded` is added too.

Here is a working [fiddle showing](https://jsfiddle.net/kdxx0fxb/) your example.

**Comment by eisbehr-** [comment]
And just to show you, there is even a way without using the `.lazy` class when you have a wrapper like `#wrap`:
https://jsfiddle.net/kdxx0fxb/1/

**Comment by eisbehr-** [comment]
Thanks for your feedback. I will think about this. But this is a very special usecase imo. 😉

**Comment by jasomdotnet** [comment]
Lazy loading CSS sprites for example.
